
(function(){
const root=document.getElementById('wedding-pages');
const q=s=>root.querySelector(s), qa=s=>Array.from(root.querySelectorAll(s));
const assets=window.WEDDING_ASSETS;
const pools=[
{role:'TOP',list:[['Malphite','말파이트','산더미 빨래','단단한 라인전'],['Garen','가렌','주말 대청소','청소기를 돌려라'],['Ornn','오른','가구 조립','신혼집 업그레이드'],['Nasus','나서스','쌓이는 집안일','오늘도 스택 쌓는 중'],['Renekton','레넥톤','한여름 더위','에어컨 쿨타임 없음']]},
{role:'JUNGLE',list:[['Nocturne','녹턴','월요일 출근','월요일이 찾아옵니다'],['Amumu','아무무','주말 종료','일요일 밤의 눈물'],['Warwick','워윅','야식의 유혹','치킨 냄새 추적 중'],['Rammus','람머스','출근길 정체','굴러가긴 합니다'],['LeeSin','리 신','사라진 리모컨','분명 여기에 있었는데']]},
{role:'MID',list:[['Brand','브랜드','오늘 저녁 뭐 먹지','주방 점화 준비'],['Annie','애니','냄비 위의 찌개','불 조절이 필요합니다'],['Veigar','베이가','배달비 누적','주문할수록 강해짐'],['Yasuo','야스오','널어둔 빨래','바람이 필요합니다'],['Ahri','아리','세일 알림','장바구니 매혹 중']]},
{role:'BOTTOM',list:[['Draven','드레이븐','장바구니 물가','골드가 필요합니다'],['Jinx','징크스','택배 개봉','신나서 지르는 중'],['Ashe','애쉬','겨울 난방비','지갑까지 얼어붙음'],['Ezreal','이즈리얼','주말 여행 계획','어디로 떠나볼까'],['Caitlyn','케이틀린','가계부 점검','빠진 지출 포착']]},
{role:'SUPPORT',list:[['Blitzcrank','블리츠크랭크','이불의 유혹','출근 전 그랩 주의'],['Thresh','쓰레쉬','늦잠의 사슬','침대에서 못 나가는 중'],['Leona','레오나','아침 햇살','강제 기상 준비'],['Nautilus','노틸러스','월요병','발걸음이 무겁습니다'],['Lulu','룰루','늘어나는 짐','짐아, 커져라!']]}
];
let username='하객소환사',icon='Teemo',page='login',galleryIndex=0,team=[],running=false,timer=null,started=0,lastHit=-Infinity,score=0,cs=0,cannon=0,combo=0,maxCombo=0,targets=[],records=[];
const photoKeys=Array.from({length:9},(_,i)=>'wedding'+i);
qa('[data-photo]').forEach(el=>el.src=assets[el.dataset.photo]);
function portrait(key,alt){const img=document.createElement('img');img.src=assets[key];img.alt=alt;return img;}
function updateUser(){qa('[data-nickname]').forEach(el=>el.textContent=username);q('#wedding-my-icon').src=assets[icon];}
['Teemo','Ahri','Ezreal','Lulu'].forEach(key=>{const b=document.createElement('button');b.className='icon-select';b.type='button';b.setAttribute('aria-label',({Teemo:'티모',Ahri:'아리',Ezreal:'이즈리얼',Lulu:'룰루'})[key]);b.setAttribute('aria-pressed',String(key===icon));b.append(portrait(key,b.getAttribute('aria-label')));b.addEventListener('click',()=>{icon=key;qa('.icon-select').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));updateUser();});q('#wedding-icons').append(b);});
function rollTeam(){team=pools.map((pool,i)=>{const options=pool.list.filter(x=>!team[i]||x[0]!==team[i][0]);return options[Math.floor(Math.random()*options.length)];});q('#wedding-enemies').replaceChildren();team.forEach((item,i)=>{const row=document.createElement('div');row.className='player';const avatar=document.createElement('div');avatar.className='avatar';avatar.append(portrait(item[0],item[1]));const copy=document.createElement('div');copy.className='player-copy';for(const [cls,value]of [['status',item[3]],['player-name',item[2]],['role',pools[i].role+' · '+item[1]]]){const el=document.createElement('div');el.className=cls;el.textContent=value;copy.append(el);}row.append(avatar,copy);q('#wedding-enemies').append(row);});}
function stopGame(){running=false;clearInterval(timer);timer=null;}
function show(next,push=true){if(push&&next!==page){try{history.pushState({weddingScreen:next==='game'?'guide':next},'', '#'+next);}catch(_){}} if(page==='game'&&next!=='game')stopGame();page=next;qa('[data-screen]').forEach(el=>el.hidden=el.dataset.screen!==next);qa('.preview-nav [data-go]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.go===next)));q('#wedding-toast').hidden=true;const current=q('[data-screen="'+next+'"]');if(current){current.focus({preventScroll:true});}window.scrollTo({top:0,behavior:'instant'});if(next==='game'&&!running){q('#wedding-game-start').hidden=false;} }
qa('[data-go]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.go)));
function login(guest){const value=q('#wedding-nickname').value.trim().slice(0,16);if(!guest&&!value){q('#wedding-login-error').textContent='소환사명을 입력해주세요.';q('#wedding-nickname').focus();return;}username=guest?'게스트':value;q('#wedding-login-error').textContent='';updateUser();rollTeam();show('queue');try{localStorage.setItem('wedding-nickname',username);localStorage.setItem('wedding-icon',icon);}catch(_){} window.dispatchEvent(new CustomEvent('wedding:login',{detail:{name:username}}));}
q('#wedding-login').addEventListener('click',()=>login(false));q('#wedding-guest').addEventListener('click',()=>login(true));q('#wedding-nickname').addEventListener('keydown',e=>{if(e.key==='Enter')login(false);});q('#wedding-reroll')?.addEventListener('click',()=>{rollTeam();show('lobby');});
function gallery(){q('#wedding-gallery-photo').src=assets[photoKeys[galleryIndex]];q('#wedding-photo-count').textContent=String(galleryIndex+1).padStart(2,'0')+' / '+String(photoKeys.length).padStart(2,'0');qa('.gallery-thumbs button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===galleryIndex)));}
photoKeys.forEach((key,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',String(i+1)+'번째 사진');b.append(portrait(key,'추억 사진 '+(i+1)));b.addEventListener('click',()=>{galleryIndex=i;gallery();});q('#wedding-thumbs').append(b);});q('#wedding-photo-prev').addEventListener('click',()=>{galleryIndex=(galleryIndex+photoKeys.length-1)%photoKeys.length;gallery();});q('#wedding-photo-next').addEventListener('click',()=>{galleryIndex=(galleryIndex+1)%photoKeys.length;gallery();});
const minionArt='<span class="minion-model" aria-hidden="true">◆</span>';
for(let i=0;i<3;i++){const b=document.createElement('button');b.className='minion';b.type='button';b.innerHTML='<div class="hp-track"><span class="hp"></span></div>'+minionArt+'<span class="minion-label">일반 미니언</span>';b.addEventListener('click',()=>hit(i));q('#wedding-wave').append(b);}
function resetTarget(i,generation=0){targets[i]={hp:100,spawn:performance.now(),delay:1.7+i*.42,generation,cannon:(generation+i)%4===2};}
function paint(){q('#wedding-score').textContent=score.toLocaleString();q('#wedding-cs').textContent=cs;qa('.minion').forEach((b,i)=>{const t=targets[i];b.classList.toggle('killable',t.hp<=25);b.querySelector('.hp').style.width=Math.max(0,t.hp)+'%';b.querySelector('.minion-label').textContent=t.cannon?'대포 · 300점':'일반 · 100점';b.setAttribute('aria-label',(t.cannon?'대포':'일반')+' 미니언, 체력 '+Math.ceil(t.hp));});}
function finish(){stopGame();q('#wedding-time').textContent='0.0';q('#wedding-result-score').textContent=score.toLocaleString();q('#wedding-result-cs').textContent=cs;q('#wedding-result-cannon').textContent=cannon;q('#wedding-result-combo').textContent=maxCombo;q('#wedding-result-label').textContent='방금 완료한 20초 플레이';q('#wedding-result-title').textContent=cs>=16?'대포를 지배한 하객':cs>=8?'우리팀으로 모십니다':'다음 판은 캐리각';const best=records.find(r=>r.name===username);if(best){best.score=Math.max(best.score,score);}else{records.push({name:username,score});}records.sort((a,b)=>b.score-a.score);q('#wedding-score-list').replaceChildren();records.slice(0,5).forEach((r,i)=>{const li=document.createElement('li');const name=document.createElement('span');name.textContent=(i+1)+'. '+r.name;const value=document.createElement('span');value.textContent=r.score.toLocaleString()+'점';li.append(name,value);q('#wedding-score-list').append(li);});show('result');window.dispatchEvent(new CustomEvent('wedding:result',{detail:{name:username,score,cs,cannon,maxCombo}}));}
function tick(){const now=performance.now();const remaining=20-(now-started)/1000;if(remaining<=0){finish();return;}q('#wedding-time').textContent=remaining.toFixed(1);targets.forEach((t,i)=>{const delta=(now-t.spawn)/1000;t.hp=100-delta/t.delay*100-(t.damage||0);if(t.hp<=0){combo=0;q('#wedding-feedback').textContent=t.cannon?'대포를 놓쳤습니다…':'막타를 놓쳤습니다';resetTarget(i,t.generation+1);}});paint();}
function hit(i){if(!running)return;const now=performance.now();if(now-started>=20000){finish();return;}if(now-lastHit<300)return;lastHit=now;const t=targets[i];const hp=100-(now-t.spawn)/1000/t.delay*100-(t.damage||0);if(hp<=0){combo=0;resetTarget(i,t.generation+1);paint();return;}if(hp<=25){const gain=(t.cannon?300:100)+Math.min(combo,5)*20;score+=gain;cs++;if(t.cannon)cannon++;combo++;maxCombo=Math.max(combo,maxCombo);q('#wedding-feedback').textContent='+'+gain+' · '+combo+'연속 막타!';resetTarget(i,t.generation+1);}else{t.damage=(t.damage||0)+25;t.hp=hp-25;q('#wedding-feedback').textContent='평타 적중 · 다음 공격까지 0.3초';}paint();}
function start(){stopGame();score=cs=cannon=combo=maxCombo=0;lastHit=-Infinity;for(let i=0;i<3;i++)resetTarget(i);started=performance.now();running=true;show('game');q('#wedding-game-start').hidden=true;q('#wedding-feedback').textContent='금색 체력 구간에 터치하세요!';q('#wedding-time').textContent='20.0';paint();timer=setInterval(tick,50);}
q('#wedding-start').addEventListener('click',start);q('#wedding-game-start').addEventListener('click',start);q('#wedding-retry').addEventListener('click',start);

try{const saved=localStorage.getItem('wedding-nickname');if(saved)q('#wedding-nickname').value=saved.slice(0,16);const savedIcon=localStorage.getItem('wedding-icon');if(['Teemo','Ahri','Ezreal','Lulu'].includes(savedIcon)){const labels={Teemo:'티모',Ahri:'아리',Ezreal:'이즈리얼',Lulu:'룰루'};q('.icon-select[aria-label="'+labels[savedIcon]+'"]').click();}}catch(_){}
try{history.replaceState({weddingScreen:'login'},'',location.pathname+location.search);}catch(_){}
window.addEventListener('popstate',event=>{const target=event.state?.weddingScreen||'login';show(q('[data-screen="'+target+'"]')?target:'login',false);window.dispatchEvent(new Event('wedding:navigate'));});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){stopGame();show('guide');}});
for(let i=0;i<3;i++)resetTarget(i);updateUser();rollTeam();gallery();paint();
})();
